working yml

diff --git a/.github/workflows/ci_manual_allure.yml b/.github/workflows/ci_manual_allure.yml
--- a/.github/workflows/ci_manual_allure.yml
+++ b/.github/workflows/ci_manual_allure.yml
@@ -1,43 +1,57 @@
-name: Run tests manual with allure report
+name: Run tests manual with Allure report
 
 on:
-  workflow_dispatch: 
+  workflow_dispatch:
 
-jobs: 
+jobs:
   build:
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-      
-    - name: Build the Docker image
-      run: docker build -t saucedemo_ci . 
-      
-    - name: Run the Docker container
-      run: docker run saucedemo_ci
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Build the Docker image
+        run: docker build -t saucedemo_ci .
+
+      - name: Run the Docker container
+        run: docker run --name saucedemo_ci -v $(pwd)/allure-results:/demo/allure-results saucedemo_ci
+
+      # - name: Debug - List contents of allure-results
+      #   if: ${{ always() || failure() }}
+      #   run: ls -R allure-results
+
+      - name: Archive Allure results
+        if: ${{ always() || failure() }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: allure-results
+          path: allure-results
 
   allure-report:
     runs-on: ubuntu-latest
-
+    needs: build
+    if: ${{ always() || failure() }}
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Generate Allure Report
-      uses: simple-elf/allure-report-action@master
-      with:
-        allure-results: allure-results
-        gh_pages: gh-pages
-        allure_report: allure-report
-        allure_history: allure-results/history
-        keep_reports: 20
-        alluredoc_repo: https://github.com/${{ github.repository }}
-        gh_token: ${{ secrets.ALLURE_REPORT_TOKEN }}
+      - name: Install Allure
+        run: |
+          sudo wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
+          sudo tar -zxvf allure-2.25.0.tgz -C /opt/
+          sudo ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure
 
-    - name: Deploy report to GitHub Pages
-      uses: peaceiris/actions-gh-pages@v3
-      with:
-        github_token: ${{ secrets.ALLURE_REPORT_TOKEN }}
-        publish_dir: allure-results
-        publish_branch: gh-pages
+      - name: Download Allure results
+        uses: actions/download-artifact@v3
+
+      - name: Generate Allure Report
+        run: |
+          allure generate -c allure-results -o allure_report
+
+      - name: Deploy report to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.ALLURE_REPORT_TOKEN }}
+          publish_dir: allure_report
+          publish_branch: gh-pages
